onlineLibrary/LibraryApp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name= "library"

urlpatterns = [
    path('all-books/', views.book_info, name='all_books'),
    path('add-book/', views.add_book, name='add_book')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlineLibrary/LibraryProject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ViewApp.urls')),
    path('', include('LibraryApp.urls'))
]

onlineLibrary/ViewApp/urls.py
from django.urls import path
from . import views

app_name= "view"

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('show-reviews/', views.show_review, name='show_review'),
    path('add-review/', views.add_review, name='add_review'),
    path('delete/<book_id>', views.delete, name='delete'),
    path('edit/<book_id>', views.edit, name='edit'),
]

onlineLibrary/LibraryApp/models.py
from django.db import models


class Book(models.Model):
    publisher = models.CharField(max_length=20)
    namebook = models.CharField(max_length=30)
    description = models.TextField(help_text="Here is the description of the book")
    # pub_date = models.DateField(, help_text = "The is date publication")
    book = models.FileField(upload_to='books/pdf/')
    image = models.ImageField(upload_to='books/images/')

    def __str__(self):
        return self.publisher + " " + self.namebook

onlineLibrary/ViewApp/models.py
from django.db import models
from LibraryApp.models import Book
from django.utils import timezone

'''
class ViewBook(models.Model):
    namebook = models.CharField(max_length=30, help_text="The is book name")
    book = models.ImageField(upload_to='pdf')

    def __str__(self):
        return self.namebook
'''


class Review(models.Model):
    name = models.CharField(verbose_name="name", max_length=50, default="anonymous")
    comment = models.TextField(max_length=200)
    review_date = models.DateTimeField(default=timezone.now)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

onlineLibrary/LibraryApp/forms.py
from django import forms
from .models import Book


class AddBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

onlineLibrary/ViewApp/forms.py
from .models import Review
from django import forms


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"

onlineLibrary/LibraryApp/views.py
from django.shortcuts import render, redirect, resolve_url
from .models import Book
from .forms import AddBookForm


# this function to show all books
def book_info(request):
    books = Book.objects.all()
    context = {'books': books}
    return render(request, "library.html", context)


# this function to add books to database
def add_book(request):
    if request.method == "POST":
        form = AddBookForm(request.POST)
    else:
        form = AddBookForm()
    if request.method == "POST":
        form = AddBookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(resolve_url("library:all_books"))
    form = AddBookForm()
    context = {"form": form}
    return render(request, "add-book.html", context)

    '''
    if request.method == 'POST':
        print('hellooooooo')
        addForm = AddBookForm(request.POST)

        if addForm.is_valid(): # the issue from here.some model fields are causing invalid
            addForm.save()
            return redirect(resolve_url("library:all_books"))

    form = AddBookForm()
    context = {"form": form}
    return render(request, "add-book.html", context)
    '''

onlineLibrary/ViewApp/views.py
from django.shortcuts import render, redirect, resolve_url
from .models import Review
from .forms import ReviewForm


def home(request):
    return render(request, "home.html")


def about(request):
    return render(request, "about.html")


# show the reviews
def show_review(request):
    reviews = Review.objects.all()
    context = {'reviews': reviews}
    return render(request, "show-reviews.html", context)


# add form works correctly, it adds the review to the database :)
def add_review(request):
    if request.method == "POST":
        form = ReviewForm(request.POST)
    else:
        form = ReviewForm()
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(resolve_url("view:show_review"))
    form = ReviewForm()
    context = {"form": form}
    return render(request, "add-review.html", context)


# delete the review
def delete(request, book_id):
    item = Review.objects.get(pk=book_id)
    item.delete()
    return redirect(resolve_url("view:show_review"))


'''
# to edit the review
def edit(request, book_id):
    if request.method == "POST":
        item = Review.objects.get(pk=book_id)
        form = ReviewForm(request.POST or None, instance=item)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        item = Review.objects.get(pk=book_id)
    return render(request, 'edit-review.html', {'item': item})
'''


def edit(request, book_id):
    item = Review.objects.get(id=book_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('view:edit', item.id)
    else:
        form = ReviewForm(instance=item)
    return render(request,
                  'edit-review.html',
                  {'form': form})

onlineLibrary/LibraryApp/templates/add-book.html
{% extends "home.html" %}
{% load static %}

{% block title %} Add Book {% endblock %}

{% block content %}
<body id= "bk" style="background-image: url({% static 'images/background2.png' %})">
<br>
<h1 style="text-align: center"> Add Book </h1>

<div class="container margin: auto">
    <div style="margin-left: 100px; margin-top: 50px">
    <form action="{% url 'library:all_books' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    </div>
</div>
</body>
{% endblock %}

onlineLibrary/LibraryApp/templates/library.html
{% extends "home.html" %}
{% load static %}

{% block title %} Library of Books {% endblock %}

{% block content %}
<body >
<h2 style="text-align: center"> All Books </h2>



{% if books %}
<div style="margin-left: 150px">
    {% for book in books %}
<!-- card 1 -->
<div class="row" style="margin: 0 -5px; display: block">
  <div class="column" style="float: left; width: 30%; padding: 0 10px"">

    <div class="card1">
<div class="star">
    <div class="body">
<div class="wrapper">
    <div class="card">
        <img src="{{ book.image.url }}">
        <div class="info" style="margin-top: -30px">
            <h1>{{ book.namebook }}</h1>
            <p> {{ book.description }} </p>
            <h6 style="margin-top: -10px"> shared by: {{ book.publisher }}</h6>
            <a href="#" class="btn"> Read it </a>
        </div>
    </div>
</div>
</div>
</div>
    </div>
</div>
<!-- end of card-->
    {% endfor %}
</div>
{% else %}
        <p style="text-align: center"> No Books Available ..</p>
{% endif %}


</body>
{% endblock %}

onlineLibrary/ViewApp/templates/about.html
{% extends "home.html" %}
{% load static %}

{% block title %} About {% endblock %}

{% block content %}
<body id= "bk"  style="background-image: url({% static 'images/background2.png' %})">
<br>
  <h2 style="text-align: center"> Who Are We? </h2>
   <p style="text-align: center"> Magic Brains Library is owned by book addicts. <br>
   Our mission is to spread the habit of reading books (As easy, as possible).
   </p>
<br>
<h2 style="text-align: center"> What is your role? </h2>
<p style="text-align: center"> As a reader, you can read and share what you think about any book in the online library.</p>
<p style="text-align: center"> As a reader, you can share BOOKS TOO! This can help our organization to become wider.</p>
<h5 style="text-align: left; margin-top:100px; margin-left:100px; color: orange"> Contact :</h5>
<a style="text-align: left; margin-top:110px; margin-left:100px ; color: gray"> MagicBrains@gmail.com </a>
<br>
<a style="text-align: left; margin-top:100px; margin-left:100px; color: gray"> Tel: +966 50 444 349</a>
</body>
{% endblock %}

onlineLibrary/ViewApp/templates/add-review.html
{% extends "home.html" %}
{% load static %}

{% block title %} Add Reviews {% endblock %}

{% block content %}
<body id= "bk" style="background-image: url({% static 'images/background2.png' %})">
<br>
<h2 style="text-align: center"> Add Review </h2>
<div style="margin-left: 100px; margin-top: 100px">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        <input type="submit" name="submit_input" Value="Submit">
    </p>
</form>
    </div>


</body>
{% endblock %}

onlineLibrary/ViewApp/templates/edit-review.html
{% extends "home.html" %}
{% load static %}

{% block title %} Edit Review {% endblock %}

{% block content %}
<body id= "bk" style="background-image: url({% static 'images/background2.png' %})">
<br>
<h2 style="text-align: center"> Edit Review </h2>
<div style="margin-left: 100px; margin-top: 100px">

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">

      <a href="{% url 'view:show_review' %}" style="color: lightslategray; margin-left: 20px"> Show All Reviews </a>
 </form>

</body>
{% endblock %}

onlineLibrary/ViewApp/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <meta charset="UTF-8">
    {% block contect %}
    <title>{% block title %} Home {% endblock %}</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">

  <div class="container-fluid">
            <!--icon or logo-->
      <nav class="navbar navbar-light bg-light">
       <a class="navbar-brand" href="#">
       <img src="{% static 'images/logo book.png' %}" width="50" height="40" alt="">
        </a></nav>

    <a class="navbar-brand" href="{% url 'view:home' %}">Magic Brains Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'view:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'view:about' %}">About</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'view:add_review' %}">Add Review</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Library
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'library:all_books' %}"> All books </a></li>
            <li><a class="dropdown-item" href="{% url 'library:add_book' %}"> Add book </a></li>
          </ul>
        </li>
      </ul>



      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</div>

</head>


{% block content %} <!--page-specific code-->
<body id= "bk" style="background-image: url({% static 'images/background1.png' %})" >
<div class="welcome">
<img src="{% static 'images/Welcome.png' %}">
    <h3> Check out our recent choices of amazing books. </h3>
</div>

<div class="container">




<!-- card 1 -->
    <div class="card1">
<div class="star">
    <div class="body">
<div class="wrapper">
    <div class="card">
        <img src="{% static 'images/queen-cover.jpg' %}">
        <div class="info">
            <h1>The Queen's Gambit</h1>
            <p> an American novel, exploring the life of fictional female chess prodigy Beth Harmon.</p>
            <a href="{% static 'pdf/queen gambit.pdf' %}" class="btn"> Read it </a>
        </div>
    </div>
</div>
</div>
</div>
<!-- end of card-->
        </div>
<br>

<!-- card 2 -->
      <div class="card2">
<div class="star">
    <div class="body">
<div class="wrapper">
    <div class="card">
        <img src="{% static 'images/harry-cover.jpeg' %}">
        <div class="info">
            <h1>Harry Potter</h1>
            <p> The novels chronicle the lives of a young wizard, Harry Potter, and his friends.</p>
            <a href="{% static 'pdf/HP_Book1_Chapter_Excerpt.pdf' %}" class="btn"> Read it </a>
        </div>
    </div>
</div>
</div>
</div>
<!-- end of card-->
         </div>
<br>
<!-- card 3 -->
    <div class="card3">
<div class="star">
    <div class="body">
<div class="wrapper">
    <div class="card">
        <img src="{% static 'images/stars-cover.jpg' %}">
        <div class="info">
            <h1>The Fault in Our Stars</h1>
            <p>  a 16-year-old cancer patient, meets a young boy.</p>
            <a href="{% static 'pdf/The Fault in Stars.pdf' %}" class="btn"> Read it </a>
        </div>
    </div>
</div>
</div>
</div>
<!-- end of card-->
        </div>
</div>




<div id="footer">

</div>


</body>
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</html>

onlineLibrary/ViewApp/templates/show-reviews.html
{% extends "home.html" %}
{% load static %}

{% block title %} Show Reviews {% endblock %}

{% block content %}
<body id= "bk" style="background-image: url({% static 'images/background2.png' %})">
<br>
<h3 style="text-align: center"> Thank you!! your review for the book is added. </h3>

<!-- for loop to show our reviews from views-->
<div style="border-style:ridge; width: 800px; margin-left: 50px; margin-top: 50px;">
{% if reviews %}
{% for review in reviews %}
    <div style="border-style:ridge;">
    <h6> ({{ review.name }}): {{ review.comment }}</h6>
    <p style="color: gray"> {{review.review_date}}, Review of the book: {{review.book.namebook}}</p>
        <a href="{% url 'view:delete' review.id %} " style="margin-left: 1em; color: coral;"> Delete </a>

        <a href="{% url 'view:edit' review.id %}" style="margin-left: 2em; color: cadetblue;" > Edit </a>
        <a href="{% url 'view:edit' review.id %} "> {{ review.item }} </a>

</div>

{% endfor %}

{% else %}
<p style="text-align: center"> No Reviews yet! </p>
{% endif %}
</div>

</body>
{% endblock %}

onlineLibrary/ViewApp/templates/view-book.html
{% extends "home.html" %}
{% load static %}

{% block title %} View Book {% endblock %}

{% block content %}
<body>
<h1> This page should display pdf file as a readable book</h1>

<button type="button" class="btn btn-secondary">Secondary</button>
{% endblock %}